#!/usr/bin/env python3
"""Build the self-hosted lk-unlock web bundle.
Run: uv run python web/build.py
Network is needed ONLY at build time; the runtime is fully offline.
Output: web/pyodide/, web/vendor/pyasn1-*.whl, web/gen/pyfiles.js, web/gen/vendor.json
"""

import json
import shutil
import tarfile
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WEB = ROOT / "web"
CACHE = WEB / ".cache"
PYODIDE_VER = "0.28.3"
PYODIDE_TAR = (
    f"https://github.com/pyodide/pyodide/releases/download/"
    f"{PYODIDE_VER}/pyodide-{PYODIDE_VER}.tar.bz2"
)


def _liblk_root() -> Path:
    for p in (ROOT / "vendor/liblk/liblk", ROOT / "vendor/liblk"):
        if p.is_dir():
            return p
    raise SystemExit("liblk package not found in vendor/ - fix _liblk_root()")


SOURCES = {"lk_unlock": ROOT / "src/lk_unlock", "liblk": _liblk_root()}
EXTRA = {"patcher_web.py": WEB / "python/patcher_web.py"}


def http_get(url: str, dest: Path):
    if dest.exists():
        print(f"  cache: {dest.name}")
        return
    print(f"  GET {url}")
    dest.parent.mkdir(parents=True, exist_ok=True)
    with urllib.request.urlopen(url) as r, open(dest, "wb") as f:
        shutil.copyfileobj(r, f)


def step_pyodide():
    dist = WEB / "pyodide"
    if (dist / "pyodide.js").exists():
        print("pyodide/ already present")
        return
    tb = CACHE / f"pyodide-{PYODIDE_VER}.tar.bz2"
    http_get(PYODIDE_TAR, tb)
    print("Extracting Pyodide...")
    with tarfile.open(tb, "r:bz2") as t:
        t.extractall(CACHE, filter="data")
    shutil.rmtree(dist, ignore_errors=True)
    shutil.move(str(CACHE / "pyodide"), str(dist))


def step_pyasn1():
    vendor = WEB / "vendor"
    vendor.mkdir(exist_ok=True)
    if any(vendor.glob("pyasn1-*.whl")):
        print("pyasn1 wheel already present")
        return
    meta = json.load(urllib.request.urlopen("https://pypi.org/pypi/pyasn1/json"))
    ver = meta["info"]["version"]
    url = next(
        u["url"] for u in meta["releases"][ver] if u["filename"].endswith("py3-none-any.whl")
    )
    wheel = f"pyasn1-{ver}-py3-none-any.whl"
    http_get(url, vendor / wheel)
    (WEB / "gen").mkdir(exist_ok=True)
    (WEB / "gen/vendor.json").write_text(json.dumps({"wheel": wheel}))


def step_pyfiles():
    files = {}
    for pkg, root in SOURCES.items():
        for p in sorted(root.rglob("*.py")):
            files[f"{pkg}/{p.relative_to(root).as_posix()}"] = p.read_text()
        for p in sorted(root.rglob("*.pem")):  # xiaomi.pem and other key data
            files[f"{pkg}/{p.relative_to(root).as_posix()}"] = p.read_text()
    for name, p in EXTRA.items():
        files[name] = p.read_text()
    gen = WEB / "gen"
    gen.mkdir(exist_ok=True)
    out = gen / "pyfiles.js"
    out.write_text(
        "// auto-generated by web/build.py - do not edit\n"
        "self.__PYFILES__ = " + json.dumps(files, ensure_ascii=False) + ";\n"
    )
    print(f"pyfiles.js: {len(files)} files, {out.stat().st_size // 1024} KB")


def step_adb_module():
    """Inline the vendored browser ADB module into index.html as a classic
    script (build-time only; runtime stays offline)."""
    html_path = WEB / "index.html"
    html = html_path.read_text()
    marker_start = "  // ── Custom ADB-over-WebUSB implementation ─────────────────────────────"
    anchor = "  // Wire the module's packet logger to the on-page log + toggle."
    if marker_start not in html or anchor not in html:
        raise SystemExit("ADB module markers not found in index.html - build layout changed")
    # Classic build: strip the trailing `export { ... }` block so all names
    # become globals (matches how the module is used on the site).
    module_src = (WEB / "vendor/adb-daemon-browser.js").read_text()
    export_idx = module_src.find("\nexport {\n")
    if export_idx != -1:
        module_src = module_src[:export_idx]
    # Idempotent: don't double-inject on rebuilds.
    start = html.index(marker_start)
    injected_end = html.find(anchor)
    if injected_end == -1 or injected_end < start:
        raise SystemExit("packet logger anchor not found after module marker")
    injected = (
        marker_start
        + "\n  // Inlined from vendor/adb-daemon-browser.js by web/build.py - do not edit.\n"
        + "  // Sync source: scripts/sync-adb-module.sh (github.com/tayuLuc/ya-webadb)\n"
        + module_src.rstrip()
        + "\n\n"
    )
    html = html[:start] + injected + html[injected_end:]
    html_path.write_text(html)
    print(f"index.html: inlined ADB module ({len(module_src)} bytes)")


if __name__ == "__main__":
    print("== build lk-unlock web ==")
    step_pyodide()
    step_pyasn1()
    step_pyfiles()
    step_adb_module()
    (WEB / ".nojekyll").touch()
    print("Done. Local check: uv run python -m http.server -d web 8000")
